### This notebook will cover the following steps:

1. Import the datasets into Jupyter
2. Check the dimensions of the imported dataframes
3. Combine the dataframe
4. Confirm the Merge Using the Merge Flag
5. Export the Merged Dataframe

# Import Libraries

In [2]:
import pandas as pd
import numpy as np
import os

# Import Dataframes

In [17]:
# Create Path
path = '/Users/muhammaddildar/Desktop/03-2025 Instacart Basket Analysis'

In [19]:
# Import dataset orders_products_combined.pkl
df_ords_prods_combined = pd.read_pickle(os.path.join(path, 'Data', 'Prepared Data', 'orders_products_combined.pkl'))

In [21]:
# Import the cleaned products data
df_products = pd.read_csv(os.path.join(path, 'Data', 'Prepared Data', 'products_cleaned.csv'))

# Check the dimensions of the imported dataframes

In [30]:
# Check the first few rows of each dataframe to ensure they've loaded correctly
df_products.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
1,2,All-Seasons Salt,104,13,9.3
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5
4,5,Green Chile Anytime Sauce,5,13,4.3

In [46]:
# Check the first few rows of each dataframe to ensure they've loaded correctly
df_ords_prods_combined.head()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,_merge
0,2539329,1,1,2,8,NaN,196,1,0,both
1,2539329,1,1,2,8,NaN,14084,2,0,both
2,2539329,1,1,2,8,NaN,12427,3,0,both
3,2539329,1,1,2,8,NaN,26088,4,0,both
4,2539329,1,1,2,8,NaN,26405,5,0,both

In [32]:
# 3. Check the dimensions of the imported dataframes
print(f"Orders & Products Combined Dataframe Shape: {df_ords_prods_combined.shape}")
print(f"Products Dataframe Shape: {df_products.shape}")

Orders & Products Combined Dataframe Shape: (32434489, 11)
Products Dataframe Shape: (49686, 5)

# Combine the dataframe

In [42]:
df_ords_prods_merge = df_ords_prods_combined.merge(df_products, on='product_id', how='inner')

# Confirm the Merge Using the Merge Flag

In [50]:
# Check the value counts in the '_merge' column
df_ords_prods_merge['_merge'].value_counts()

_merge
both          32432460
left_only            0
right_only           0
Name: count, dtype: int64

# Export the Merged Dataframe

In [53]:
# Export the merged dataframe to pickle format
df_ords_prods_merge.to_pickle('/Users/muhammaddildar/Desktop/03-2025 Instacart Basket Analysis/Data/Prepared Data/ords_prods_merge.pkl')