# Importing Libraries

In [3]:
import pandas as pd
import numpy as np
import os

# Create Path

In [29]:
path = r'/Users/muhammaddildar/Desktop/03-2025 Instacart Basket Analysis'

# Import Data

In [36]:
df_ords = pd.read_csv(os.path.join(path, 'Data', 'Original Data', 'orders.csv'))

In [38]:
df_ords_prior = pd.read_csv(os.path.join(path, 'Data', 'Original Data', 'orders_products_prior.csv'))

In [40]:
# checking output
df_ords_prior.head()

   order_id  product_id  add_to_cart_order  reordered
0         2       33120                  1          1
1         2       28985                  2          1
2         2        9327                  3          0
3         2       45918                  4          1
4         2       30035                  5          0

In [42]:
df_ords.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [44]:
# Check dimensions of both dataframes
print(df_ords.shape)
print(df_ords_prior.shape)

(3421083, 7)
(32434489, 4)

In [46]:
# inner merge dataframe

df_merge_large = df_ords.merge(df_ords_prior, on=['order_id'], how='inner', indicator=True)

In [21]:
df_merged_large.head()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,_merge
0,2539329,1,1,2,8,NaN,196,1,0,both
1,2539329,1,1,2,8,NaN,14084,2,0,both
2,2539329,1,1,2,8,NaN,12427,3,0,both
3,2539329,1,1,2,8,NaN,26088,4,0,both
4,2539329,1,1,2,8,NaN,26405,5,0,both

In [48]:
# examining value counts on '_merge' column

df_merged_large['_merge'].value_counts()

_merge
both          32434489
left_only            0
right_only           0
Name: count, dtype: int64

# Export Data

In [51]:
df_merge_large.to_pickle('/Users/muhammaddildar/Desktop/03-2025 Instacart Basket Analysis/Data/Prepared Data/orders_products_combined.pkl')